// nxapp/app/products/page.tsx
"use client";
import { useEffect, useState } from "react";

type Product = {
  title: string;
  description: string;
  images?: string[];
};

export default function Products() {
  const [product, setProduct] = useState<Product | null>(null);

  useEffect(() => {
    async function fetchProduct() {
      const res = await fetch("https://dummyjson.com/products/1");
      const data = await res.json();
      setProduct(data);
    }
    fetchProduct();
  }, []);

  if (!product) return <div className="product-card">Loading product...</div>;

  return (
    <div className="product-card">
      <h2>{product.title}</h2>
      <p>{product.description}</p>
      {product.images?.[0] && (
        <img src={product.images[0]} alt={product.title} />
      )}
    </div>
  );
}

// ngapp/src/app/products/products.component.ts
import { Component, OnInit } from '@angular/core';
import { HttpClient } from '@angular/common/http';

@Component({
  selector: 'app-products',
  templateUrl: './products.component.html',
  styleUrls: ['./products.component.css']
})
export class ProductsComponent implements OnInit {
  product: any = null;
  loading = true;
  error: string | null = null;

  constructor(private http: HttpClient) {}

  ngOnInit() {
    this.http.get('https://dummyjson.com/products/1').subscribe({
      next: (data) => {
        this.product = data;
        this.loading = false;
      },
      error: (err) => {
        this.error = 'Failed to load product';
        this.loading = false;
      }
    });
  }
}

<div style="margin:16px;">
  <div *ngIf="loading">Loading product...</div>
  <div *ngIf="error">{{ error }}</div>
  <div *ngIf="product">
    <h3>{{ product.title }}</h3>
    <p>{{ product.description }}</p>
    <p><strong>Price:</strong> {{ product.price }} USD</p>
    <img *ngIf="product.images?.length" [src]="product.images[0]" alt="{{product.title}}" style="max-width:200px;">
  </div>
</div>
