// ngapp/src/app/child/child.component.ts
import { Component, Input } from '@angular/core';

@Component({
  selector: 'app-child',
  templateUrl: './child.component.html',
  styleUrls: ['./child.component.css']
})
export class ChildComponent {
  @Input() states: string[] = [];
}

<div class="child-box">
  <p><strong>States passed from parent:</strong></p>
  <ul>
    <li *ngFor="let s of states">{{ s }}</li>
  </ul>
</div>

// nxapp/app/child/page.tsx
type ChildProps = {
  states: string[];
};

export default function Child({ states = [] }: ChildProps) {
  return (
    <div className="child-box">
      <p><strong>States passed from parent:</strong></p>
      <ul>
        {states.map((state, index) => (
          <li key={index}>{state}</li>
        ))}
      </ul>
    </div>
  );
}
