// ngapp/src/app/app.component.ts
import { Component } from '@angular/core';
import { Router } from '@angular/router';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  states = ['Tozeur', 'Tunis', 'Nabeul'];

  constructor(private router: Router) {}

  gotoLogin() {
    this.router.navigate(['/login']);
  }

  gotoContact() {
    this.router.navigate(['/contact', 123]);
  }
}

<app-header></app-header>

<div class="center-buttons">
  <button (click)="gotoLogin()">Login Page</button>
  <button (click)="gotoContact()">Contact Page</button>
</div>

<app-child [states]="states"></app-child>

<router-outlet></router-outlet>

// nxapp/app/page.tsx
"use client";

import { useRouter } from "next/navigation";
import { useState } from "react";
import Header from "./header";
import Child from "./child/page";
import Products from "./products/page";

export default function Home() {
  const router = useRouter();
  const [states] = useState(["Tozeur", "Gafsa", "Tunis"]);

  return (
    <>
      <Header />

      <div style={{ textAlign: "center", marginBottom: 20 }}>
        <button onClick={() => router.push("/login")}>Login Page</button>
        <button onClick={() => router.push("/contact/123")}>Contact Page</button>
      </div>

      <Child states={states} />
      <Products />
    </>
  );
}
